from dataclasses import dataclass, field
from functools import partial

from opentelemetry import metrics
from opentelemetry.metrics import Counter, Histogram

from letta.helpers.singleton import singleton
from letta.otel.metrics import get_letta_meter


@singleton
@dataclass(frozen=True)
class MetricRegistry:
    """Registry of all application metrics

    Metrics are composed of the following:
        - name
        - description
        - unit: UCUM unit of the metric (i.e. 'By' for bytes, 'ms' for milliseconds, '1' for count
        - bucket_bounds (list[float] | None): the explicit bucket bounds for histogram metrics

        and instruments are of types Counter, Histogram, and Gauge

    The relationship between the various models is as follows:
        project_id -N:1-> base_template_id -N:1-> template_id -N:1-> agent_id
        agent_id -1:1+-> model_name
        agent_id -1:N -> tool_name
    """

    Instrument = Counter | Histogram
    _metrics: dict[str, Instrument] = field(default_factory=dict, init=False)
    _meter: metrics.Meter = field(init=False)

    def __post_init__(self):
        object.__setattr__(self, "_meter", get_letta_meter())

    def _get_or_create_metric(self, name: str, factory):
        """Lazy initialization of metrics."""
        if name not in self._metrics:
            self._metrics[name] = factory()
        return self._metrics[name]

    # (includes base attributes: project, template_base, template, agent)
    @property
    def user_message_counter(self) -> Counter:
        return self._get_or_create_metric(
            "count_user_message",
            partial(
                self._meter.create_counter,
                name="count_user_message",
                description="Counts the number of messages sent by the user",
                unit="1",
            ),
        )

    # (includes tool_name, tool_execution_success, & step_id on failure)
    @property
    def tool_execution_counter(self) -> Counter:
        return self._get_or_create_metric(
            "count_tool_execution",
            partial(self._meter.create_counter, name="count_tool_execution", description="Counts the number of tools executed.", unit="1"),
        )

    # project_id + model
    @property
    def ttft_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_ttft_ms",
            partial(self._meter.create_histogram, name="hist_ttft_ms", description="Histogram for the Time to First Token (ms)", unit="ms"),
        )

    # (includes model name)
    @property
    def llm_execution_time_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_llm_execution_time_ms",
            partial(
                self._meter.create_histogram,
                name="hist_llm_execution_time_ms",
                description="Histogram for LLM execution time (ms)",
                unit="ms",
            ),
        )

    # (includes tool name)
    @property
    def tool_execution_time_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_tool_execution_time_ms",
            partial(
                self._meter.create_histogram,
                name="hist_tool_execution_time_ms",
                description="Histogram for tool execution time (ms)",
                unit="ms",
            ),
        )

    @property
    def step_execution_time_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_step_execution_time_ms",
            partial(
                self._meter.create_histogram,
                name="hist_step_execution_time_ms",
                description="Histogram for step execution time (ms)",
                unit="ms",
            ),
        )

    # TODO (cliandy): instrument this
    @property
    def message_cost(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_message_cost_usd",
            partial(
                self._meter.create_histogram,
                name="hist_message_cost_usd",
                description="Histogram for cost of messages (usd) per step",
                unit="usd",
            ),
        )

    # (includes model name)
    @property
    def message_output_tokens(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_message_output_tokens",
            partial(
                self._meter.create_histogram,
                name="hist_message_output_tokens",
                description="Histogram for output tokens generated by LLM per step",
                unit="1",
            ),
        )

    # (includes endpoint_path, method, status_code)
    @property
    def endpoint_e2e_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_endpoint_e2e_ms",
            partial(
                self._meter.create_histogram,
                name="hist_endpoint_e2e_ms",
                description="Histogram for endpoint e2e time (ms)",
                unit="ms",
            ),
        )

    # (includes endpoint_path, method, status_code)
    @property
    def endpoint_request_counter(self) -> Counter:
        return self._get_or_create_metric(
            "count_endpoint_requests",
            partial(
                self._meter.create_counter,
                name="count_endpoint_requests",
                description="Counts the number of endpoint requests",
                unit="1",
            ),
        )

    # Headline metric for comparing the two /messages flows. Recorded inside the
    # send_message route handler (NOT the ASGI middleware) because the
    # latencyOptimisationFlow flag lives in the request body and is only known
    # there — the middleware runs the handler in a separate task, so a context
    # attribute set in the handler never propagates back up to it.
    # Attributes (all low cardinality):
    #   - latency_optimisation_flow : "true" | "false"
    #   - status_code               : HTTP status of the response
    #   plus the base ctx attributes (organization.id, project.id, agent.id, ...)
    @property
    def messages_endpoint_e2e_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_messages_endpoint_e2e_ms",
            partial(
                self._meter.create_histogram,
                name="hist_messages_endpoint_e2e_ms",
                description="End-to-end latency (ms) of POST /v1/agents/{id}/messages, partitioned by latency_optimisation_flow.",
                unit="ms",
            ),
        )

    # Per-LLM-call latency — the duration of a single provider request_async() call
    # ONLY (not the whole /messages endpoint, not memory rebuild / persistence / tool
    # execution). Recorded once per LLM call at every step of the agent loop.
    # Use this to compare provider latency in isolation, e.g. Bedrock vs the direct
    # Anthropic/inference proxy, independently of the rest of the request.
    # Attributes (all low cardinality):
    #   - use_bedrock_experiment : "true" | "false"  (Bedrock vs inference.memgpt.ai)
    #   - model.name             : the model that served this call
    #   plus the base ctx attributes (organization.id, project.id, agent.id, ...)
    @property
    def llm_call_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_llm_call_ms",
            partial(
                self._meter.create_histogram,
                name="hist_llm_call_ms",
                description="Latency (ms) of a single LLM provider call, partitioned by use_bedrock_experiment.",
                unit="ms",
                # Single-call latency lives in the 0.5-30s band (Haiku ~0.5-2s, Sonnet
                # ~2-8s, degraded Bedrock up to ~30s). Default OTel buckets cap at 10s
                # and would clip the degraded tail we specifically want to see.
                explicit_bucket_boundaries_advisory=[
                    100,
                    250,
                    500,
                    1000,
                    2000,
                    3000,
                    5000,
                    7500,
                    10000,
                    15000,
                    20000,
                    30000,
                    45000,
                    60000,
                ],
            ),
        )

    # Latency of a single OpenAI embeddings API call (client.embeddings.create),
    # recorded around the call in OpenAIEmbeddings.get_text_embedding regardless of
    # success/failure. This call runs synchronously (blocking) inside async request
    # paths like archival_memory_search, so provider-side stalls here directly stall
    # the whole event loop — this metric is what should page/alert on that, instead
    # of only surfacing after the fact via [STEP_TIMING][tool_execution] log lines.
    # Attributes (all low cardinality):
    #   - embedding_model : the configured embedding model (e.g. text-embedding-3-small)
    #   - success         : "true" | "false"
    #   plus the base ctx attributes (organization.id, project.id, agent.id, ...)
    @property
    def openai_embedding_call_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_openai_embedding_call_ms",
            partial(
                self._meter.create_histogram,
                name="hist_openai_embedding_call_ms",
                description="Latency (ms) of a single OpenAI embeddings API call, partitioned by success.",
                unit="ms",
                # Healthy calls land well under 1s; the known failure mode is
                # unbounded retries against a stalled/rate-limited provider (no
                # timeout is set on the client), which has been observed running
                # into multiple minutes — so the tail buckets need to go far past
                # the 10s ceiling of the OTel defaults.
                explicit_bucket_boundaries_advisory=[
                    50,
                    100,
                    250,
                    500,
                    1000,
                    2000,
                    3000,
                    5000,
                    10000,
                    20000,
                    30000,
                    60000,
                    120000,
                    300000,
                    600000,
                ],
            ),
        )

    # --- Haiku cascade (latencyOptimisationFlow) metrics ---
    # All attributes use low cardinality:
    #   - provider  : anthropic | anthropic_vertex | anthropic_bedrock
    #   - primary_model : the agent's primary model name (e.g. claude-sonnet-4-5-20250929)
    #   - outcome   : (step counter only) haiku_kept | primary_step0 | primary_retried | primary_no_haiku_model

    # Per-request counter — one tick per request with cascade enabled, plus a `had_retry` flag.
    @property
    def haiku_cascade_request_counter(self) -> Counter:
        return self._get_or_create_metric(
            "count_haiku_cascade_request",
            partial(
                self._meter.create_counter,
                name="count_haiku_cascade_request",
                description="Counts requests handled with the Haiku cascade (latencyOptimisationFlow=true)",
                unit="1",
            ),
        )

    # Per-step counter — one tick per step, with `outcome` attribute classifying the resolution.
    @property
    def haiku_cascade_step_counter(self) -> Counter:
        return self._get_or_create_metric(
            "count_haiku_cascade_step",
            partial(
                self._meter.create_counter,
                name="count_haiku_cascade_step",
                description="Counts agent loop steps when the Haiku cascade is active, partitioned by outcome.",
                unit="1",
            ),
        )

    # Per-request histogram of total step count (lets us see workload distribution).
    @property
    def haiku_cascade_total_steps_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_haiku_cascade_total_steps",
            partial(
                self._meter.create_histogram,
                name="hist_haiku_cascade_total_steps",
                description="Total number of steps per Haiku-cascade request",
                unit="1",
            ),
        )

    # Per-request histogram of % of steps that ran on Haiku.
    @property
    def haiku_cascade_haiku_pct_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_haiku_cascade_haiku_pct",
            partial(
                self._meter.create_histogram,
                name="hist_haiku_cascade_haiku_pct",
                description="Percentage of steps that ran on Haiku per Haiku-cascade request",
                unit="1",
            ),
        )

    # Per-retry histogram of wasted Haiku token counts (helps quantify the cost of the gate).
    @property
    def haiku_cascade_wasted_tokens_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_haiku_cascade_wasted_tokens",
            partial(
                self._meter.create_histogram,
                name="hist_haiku_cascade_wasted_tokens",
                description="Wasted Haiku tokens per retried step (Haiku call discarded, primary re-run).",
                unit="1",
            ),
        )

    # Per-request histogram of total Haiku tokens used (kept + wasted) — feeds spend dashboards.
    @property
    def haiku_cascade_haiku_tokens_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_haiku_cascade_haiku_tokens",
            partial(
                self._meter.create_histogram,
                name="hist_haiku_cascade_haiku_tokens",
                description="Total Haiku tokens used per Haiku-cascade request (kept Haiku steps only, not retries).",
                unit="1",
            ),
        )

    # Per-request histogram of total primary tokens used — pair with Haiku to compute savings.
    @property
    def haiku_cascade_primary_tokens_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_haiku_cascade_primary_tokens",
            partial(
                self._meter.create_histogram,
                name="hist_haiku_cascade_primary_tokens",
                description="Total primary-model tokens used per Haiku-cascade request.",
                unit="1",
            ),
        )

    # Per-request total latency in ms — this is the headline cascade metric.
    # Compare percentiles vs non-cascade traffic to quantify the latency win.
    # Attributes include `had_retry` so we can split "ideal path" vs "retry path"
    # and `total_steps_bucket` (1 | 2 | 3-5 | 6+) so the multi-step economics
    # are visible at a glance without needing the histogram heatmap.
    @property
    def haiku_cascade_request_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_haiku_cascade_request_ms",
            partial(
                self._meter.create_histogram,
                name="hist_haiku_cascade_request_ms",
                description="End-to-end request latency (ms) when the Haiku cascade is enabled.",
                unit="ms",
            ),
        )

    # Per-step latency in ms, tagged with outcome so we can see e.g. "Haiku kept
    # steps average X ms, primary retried steps average Y ms". Complements the
    # existing hist_step_execution_time_ms (which has no cascade-outcome label).
    @property
    def haiku_cascade_step_ms_histogram(self) -> Histogram:
        return self._get_or_create_metric(
            "hist_haiku_cascade_step_ms",
            partial(
                self._meter.create_histogram,
                name="hist_haiku_cascade_step_ms",
                description="Per-step latency (ms) when the Haiku cascade is enabled, partitioned by outcome.",
                unit="ms",
            ),
        )
